import { COLORS } from '../config'

export const uncrunchLight = {
  colors: {
    background: { DEFAULT: '#faf5f3' },
    foreground: {
      50: COLORS.uncrunch.light.foreground[50],
      100: COLORS.uncrunch.light.foreground[100],
      200: COLORS.uncrunch.light.foreground[200],
      300: COLORS.uncrunch.light.foreground[300],
      400: COLORS.uncrunch.light.foreground[400],
      500: COLORS.uncrunch.light.foreground[500],
      600: COLORS.uncrunch.light.foreground[600],
      700: COLORS.uncrunch.light.foreground[700],
      800: COLORS.uncrunch.light.foreground[800],
      900: COLORS.uncrunch.light.foreground[900],
      DEFAULT: COLORS.uncrunch.light.foreground.default,
    },
    divider: { DEFAULT: COLORS.uncrunch.light.divider },
    focus: { DEFAULT: COLORS.uncrunch.light.focus },
    overlay: { DEFAULT: COLORS.uncrunch.light.overlay },
    content1: { DEFAULT: '#fff', foreground: '#11181C' },
    content2: { DEFAULT: '#f4f4f5', foreground: '#27272a' },
    content3: { DEFAULT: '#e4e4e7', foreground: '#3f3f46' },
    content4: {
      DEFAULT: COLORS.uncrunch.light.default.default,
      foreground: '#1e539d',
    },
    default: {
      50: COLORS.uncrunch.light.default[50],
      100: COLORS.uncrunch.light.default[100],
      200: COLORS.uncrunch.light.default[200],
      300: COLORS.uncrunch.light.default[300],
      400: COLORS.uncrunch.light.default[400],
      500: COLORS.uncrunch.light.default[500],
      600: COLORS.uncrunch.light.default[600],
      700: COLORS.uncrunch.light.default[700],
      800: COLORS.uncrunch.light.default[800],
      900: COLORS.uncrunch.light.default[900],
      foreground: COLORS.uncrunch.light.default.foreground,
      DEFAULT: COLORS.uncrunch.light.default.default,
    },
    primary: {
      50: COLORS.uncrunch.light.primary[50],
      100: COLORS.uncrunch.light.primary[100],
      200: COLORS.uncrunch.light.primary[200],
      300: COLORS.uncrunch.light.primary[300],
      400: COLORS.uncrunch.light.primary[400],
      500: COLORS.uncrunch.light.primary[500],
      600: COLORS.uncrunch.light.primary[600],
      700: COLORS.uncrunch.light.primary[700],
      800: COLORS.uncrunch.light.primary[800],
      900: COLORS.uncrunch.light.primary[900],
      foreground: COLORS.uncrunch.light.primary.foreground,
      DEFAULT: COLORS.uncrunch.light.primary.default,
    },
    secondary: {
      50: COLORS.uncrunch.light.secondary[50],
      100: COLORS.uncrunch.light.secondary[100],
      200: COLORS.uncrunch.light.secondary[200],
      300: COLORS.uncrunch.light.secondary[300],
      400: COLORS.uncrunch.light.secondary[400],
      500: COLORS.uncrunch.light.secondary[500],
      600: COLORS.uncrunch.light.secondary[600],
      700: COLORS.uncrunch.light.secondary[700],
      800: COLORS.uncrunch.light.secondary[800],
      900: COLORS.uncrunch.light.secondary[900],
      foreground: COLORS.uncrunch.light.secondary.foreground,
      DEFAULT: COLORS.uncrunch.light.secondary.default,
    },
    success: {
      50: COLORS.uncrunch.light.success[50],
      100: COLORS.uncrunch.light.success[100],
      200: COLORS.uncrunch.light.success[200],
      300: COLORS.uncrunch.light.success[300],
      400: COLORS.uncrunch.light.success[400],
      500: COLORS.uncrunch.light.success[500],
      600: COLORS.uncrunch.light.success[600],
      700: COLORS.uncrunch.light.success[700],
      800: COLORS.uncrunch.light.success[800],
      900: COLORS.uncrunch.light.success[900],
      foreground: COLORS.uncrunch.light.success.foreground,
      DEFAULT: COLORS.uncrunch.light.success.default,
    },
    warning: {
      50: COLORS.uncrunch.light.warning[50],
      100: COLORS.uncrunch.light.warning[100],
      200: COLORS.uncrunch.light.warning[200],
      300: COLORS.uncrunch.light.warning[300],
      400: COLORS.uncrunch.light.warning[400],
      500: COLORS.uncrunch.light.warning[500],
      600: COLORS.uncrunch.light.warning[600],
      700: COLORS.uncrunch.light.warning[700],
      800: COLORS.uncrunch.light.warning[800],
      900: COLORS.uncrunch.light.warning[900],
      foreground: COLORS.uncrunch.light.warning.foreground,
      DEFAULT: COLORS.uncrunch.light.warning.default,
    },
    danger: {
      50: COLORS.uncrunch.light.danger[50],
      100: COLORS.uncrunch.light.danger[100],
      200: COLORS.uncrunch.light.danger[200],
      300: COLORS.uncrunch.light.danger[300],
      400: COLORS.uncrunch.light.danger[400],
      500: COLORS.uncrunch.light.danger[500],
      600: COLORS.uncrunch.light.danger[600],
      700: COLORS.uncrunch.light.danger[700],
      800: COLORS.uncrunch.light.danger[800],
      900: COLORS.uncrunch.light.danger[900],
      foreground: COLORS.uncrunch.light.danger.foreground,
      DEFAULT: COLORS.uncrunch.light.danger.default,
    },
  },
}
